apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: default
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --top-domain=imp  
        image: 716309063777.dkr.ecr.us-east-1.amazonaws.com/kafka-operator:IN-561-3
        name: manager
        ports:
        - containerPort: 9001
          name: alerts
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
